### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by kolyabres** [upwork/node-upwork-oauth2#33]
I got this error

```
/Users/mykolabreslavskyi/www/perfsol/upwork/node_modules/@upwork/node-upwork-oauth2/lib/client.js:297
    callback(err, httpResponse.statusCode, parseResponse(body));
    ^

TypeError: callback is not a function
    at Request._callback (/Users/mykolabreslavskyi/www/perfsol/upwork/node_modules/@upwork/node-upwork-oauth2/lib/client.js:297:5)
    at self.callback (/Users/mykolabreslavskyi/www/perfsol/upwork/node_modules/request/request.js:185:22)
    at Request.emit (node:events:518:28)
    at Request.<anonymous> (/Users/mykolabreslavskyi/www/perfsol/upwork/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:518:28)
    at IncomingMessage.<anonymous> (/Users/mykolabreslavskyi/www/perfsol/upwork/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:632:28)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

my code
```
function getRoom(api, roomId, callback) {
    // make a call
    var graphql = new Graphql(api);
    graphql.execute()
    var params = {
        query: `query room($roomId: ID!) {
  room(id: $roomId) {
    id
    organization {
      id
    }
    roomName
    roomType
    topic
    lastVisitedDateTime
    lastReadDateTime
    favorite
    readOnly
    hidden
    roomUsers {
      user {
        id
      }
      organization {
        id
      }
      role
    }
    stories {
      totalCount
      pageInfo {
        endCursor
      }
      edges {
        node {
          id
          createdDateTime
          updatedDateTime
          user {
            id
          }
          message
        }
      }
    }
  }
}`,
        variables: {roomId: roomId},
        operationName: "room"
    };
    graphql.execute(params, function (error, httpStatus, data) {
        // check error and httpStatus if needed and run your own error handler
        debug(httpStatus, 'response status');
        debug(data, 'received response');
        callback(data);
    });
}

getRoom(api, 'roomid',function (d){console.log(d)})
```

**Comment by mnovozhylov** [comment]
Hi,
Please, check that your "callback" is a function. See the example of usage of a GQL call here - https://github.com/upwork/node-upwork-oauth2/blob/master/example/example.js#L110

**Comment by kolyabres** [comment]
@mnovozhylov, did you see the example? it is a function
